### ISSUE TITLE
Unknown language engine 'drawio' (must be registered via knit_engines$set()).

### ISSUE THREAD

**Issue by nergiszaim** [rchaput/knitrdrawio#1]
Hi, I am running this package in a docker environment. I bind the drawio to hm home/drawio folder. However in `Rmd`, the setup doesn't apply to drawio. Any suggestions?

```
---
title: "Untitled"
output: html_document
VignetteBuilder: knitr
Suggests: knitr
---


{r setup, engine= 'drawio', engine.path = "/home/drawio"}


{drawio nz-diagram, src= "ETL-Diagram.drawio", include = TRUE, fig.path = "/test_files/figure-html"}

```

Error:

1: In get_engine(options$engine) :
  Unknown language engine 'drawio' (must be registered via knit_engines$set()).
2: In get_engine(options$engine) :
  Unknown language engine 'drawio' (must be registered via knit_engines$set()).

**Comment by rchaput** [comment]
Hello,

You must first load the library by using `library(knitrdrawio)` in a R chunk.

Also, I am not sure that your `setup` chunk works as intended, but perhaps this is a special syntax that I do not know about.
I would write it as such:
````
```{r setup}
library(knitr)
library(knitrdrawio)
knitr::opts_chunks$set(engine.path = list(
    drawio = "/home/drawio"
))
```
````

The first line loads knitr so we can set the options, the second line loads knitrdrawio (it will automatically register the engine), and the last lines set the engine path for all the drawio chunks.

**Comment by nergiszaim** [comment]
that works thanks!
