### ISSUE TITLE
Knitrdrawio does not work in headless environments (Docker, CI/CD, remote servers without displays, ...)

### ISSUE THREAD

**Issue by nergiszaim** [rchaput/knitrdrawio#2]
Hi, I am running the below code in a docker environment and I am getting the error: 

Any ideas?

**Comment by nergiszaim** [comment]
[](url
<img width="704" alt="Screen Shot 2022-04-15 at 10 08 38 AM" src="https://user-images.githubusercontent.com/58089236/163600059-39c5df0e-8467-43c8-adf3-05537c38587d.png">
)

**Comment by nergiszaim** [comment]
<img width="410" alt="Screen Shot 2022-04-15 at 10 10 28 AM" src="https://user-images.githubusercontent.com/58089236/163600250-650ca9fd-f7d7-46ec-a074-5f4545ccf973.png">

**Comment by rchaput** [comment]
Hmm, this is weird. This means that drawio should have produced the image at `test_files/figure-html/nz-diagram.svg`, but knitr does not find the file. Perhaps a problem of relative path? Can you open a shell inside your Docker and see if the file exists?

Another option could be to force the engine to use a simpler path. For example:
```{drawio nz-diagram, src="ETL-Diagram.drawio", fig.path="."}
```
This should create the diagram in the working directory. (or use `fig.path="img/"` to put the diagram in an `img/` folder).
Maybe the "test_figures" folder was deleted, but I think it is unlikely to happen just after the diagram is produced but before knit prints the image.

**Comment by nergiszaim** [comment]
your "For example` script didn't populate... I tried `fig.path="img/"` and it created the folder but I am getting the same error

**Comment by nergiszaim** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/58089236/163652535-f8e6d19f-d58d-49c7-bcae-c1cc23de0090.png">

**Comment by rchaput** [comment]
I am not sure why this doesn't work, the problem does not appear in a non-Docker context. Can you provide the Docker file you are using, so I can try and debug?

**Comment by rchaput** [comment]
Just a quick heads-up: I have been able to replicate this issue.

Apparently, draw.io requires a graphical server to work, which is missing in Docker and other "headless" environments. Basically, it means that it is complicated to run draw.io in a CI/CD pipeline.

As per the official [repository](https://github.com/jgraph/drawio-desktop/issues/146), there seems to be 2 solutions:

1. Run drawio through xvfb-run, which will simulate a virtual display. That means I must change the way drawio is invoked in this package. I will investigate on this, as it seems the best solution, but this will take some time, as we do not want to require xvfb in non-headless environments.

2. Start a virtual display server by running `xvfb &` before rendering the document. If I understand correctly, drawio should recognize there is a virtual display available. Maybe it will require to explicitly set the display, e.g., using `export DISPLAY=:1` or something like that. This can (must) be done outside the knitrdrawio package, which means this is an applicable workaround that you can use in the meantime.

**Comment by rchaput** [comment]
Sorry for the delay, there were several bugs in draw.io (or most likely electron). The new version should work in Docker containers, however, it requires Draw.io 16.0.0.
More recent versions use a version of electron that has a problem with D-Bus, as acknowledged by others: https://github.com/rlespinasse/docker-drawio-desktop-headless/issues/26

It is also required to install the `xvfb` package (through the distribution's package manager, such as `apt`).
I have included the instructions in the Readme
